compile-cls:
  image: philipptempel/docker-ubuntu-tug-texlive:latest
  stage: build
  script:
    - make clean
    - make all
  artifacts:
    name: "${CI_PROJECT_PATH_SLUG}_${CI_COMMIT_REF_NAME}"
    expire_in: 2 months
    paths:
      - dist
  tags:
    - docker

