stages:
  - build
  - demos
  - ship

ins:
  image: philipptempel/docker-ubuntu-tug-texlive:2018
  stage: build
  script:
    - make distclean
    - make all
  artifacts:
    name: "${CI_PROJECT_PATH_SLUG}_${CI_COMMIT_REF_NAME}"
    expire_in: 2 months
    paths:
      - '*.cls'
      - '*.sty'
      - '*.dict'
      - '*.pdf'
      - '*.tex'
  tags:
    - docker

demos:
  image: philipptempel/docker-ubuntu-tug-texlive:2018
  stage: demos
  script:
    - make -j 5 demos
  artifacts:
    name: "${CI_PROJECT_PATH_SLUG}_${CI_COMMIT_REF_NAME}"
    expire_in: 2 months
    paths:
      - '*.cls'
      - '*.sty'
      - '*.dict'
      - '*.pdf'
      - '*.tex'
  tags:
    - docker

release:
  image:
    name: chhinze/ghr
    entrypoint: ["/bin/sh", "-c"]
  stage: ship
  before_script:
    - 'apk add --no-cache --update alpine-sdk'
    - 'apk add --no-cache bash'
  script:
    - 'make dist'
    - 'cd $(DISTDIR)'
    - 'ghr -t ${GHR_GITHUB_TOKEN} -r ${GHR_GITHUB_REPO} -u ${GHR_GITHUB_USERNAME} -replace "${CI_BUILD_REF_NAME}" article/'
    - 'ghr -t ${GHR_GITHUB_TOKEN} -r ${GHR_GITHUB_REPO} -u ${GHR_GITHUB_USERNAME} -replace "${CI_BUILD_REF_NAME}" bachelor/'
    - 'ghr -t ${GHR_GITHUB_TOKEN} -r ${GHR_GITHUB_REPO} -u ${GHR_GITHUB_USERNAME} -replace "${CI_BUILD_REF_NAME}" book/'
    - 'ghr -t ${GHR_GITHUB_TOKEN} -r ${GHR_GITHUB_REPO} -u ${GHR_GITHUB_USERNAME} -replace "${CI_BUILD_REF_NAME}" doctorate/'
    - 'ghr -t ${GHR_GITHUB_TOKEN} -r ${GHR_GITHUB_REPO} -u ${GHR_GITHUB_USERNAME} -replace "${CI_BUILD_REF_NAME}" master/'
  only:
    - tags
  artifacts:
    name: "${CI_PROJECT_PATH_SLUG}_${CI_COMMIT_REF_NAME}"
    expire_in: 2 months
    paths:
      - '${DISTDIR}/*'
  tags:
    - docker
