stages:
  - build
  - demos
  - ship

ins:
  image: philipptempel/docker-ubuntu-tug-texlive:2018
  stage: build
  script:
    - make distclean
    - make all
  artifacts:
    name: "${CI_PROJECT_PATH_SLUG}_${CI_COMMIT_REF_NAME}"
    expire_in: 2 months
    paths:
      - '*.cls'
      - '*.sty'
      - '*.dict'
      - '*.pdf'
      - '*.tex'
  tags:
    - docker

demos:
  image: philipptempel/docker-ubuntu-tug-texlive:2018
  stage: demos
  script:
    - make -j 5 demos
  artifacts:
    name: "${CI_PROJECT_PATH_SLUG}_${CI_COMMIT_REF_NAME}"
    expire_in: 2 months
    paths:
      - '*.cls'
      - '*.sty'
      - '*.dict'
      - '*.pdf'
      - '*.tex'
  tags:
    - docker

release:
  image:
    name: chhinze/ghr
    entrypoint: ["/bin/sh", "-c"]
  stage: ship
  variables:
    DISTDIR: "dist/"
    DEMOS: "ustuttbachelor_de.tex ustuttbachelor_en.tex ustuttmaster_de.tex ustuttmaster_en.tex ustuttdoctorate_de.tex ustuttdoctorate_en.tex"
    DEMOS: "ustuttbachelor_de.pdf ustuttbachelor_en.pdf ustuttmaster_de.pdf ustuttmaster_en.pdf ustuttdoctorate_de.pdf ustuttdoctorate_en.pdf"
    ADDL_INCLUDES: "acronyms.tex symbols.tex notation.tex"
  script:
    - 'make release'
    - 'cd $(DISTDIR)'
    - 'ghr -t ${GHR_GITHUB_TOKEN} -r ${GHR_GITHUB_REPO} -u ${GHR_GITHUB_USERNAME} -replace "${CI_BUILD_REF_NAME}" release/'
    - 'ghr -t ${GHR_GITHUB_TOKEN} -r ${GHR_GITHUB_REPO} -u ${GHR_GITHUB_USERNAME} -replace "${CI_BUILD_REF_NAME}" bachelor/'
    - 'ghr -t ${GHR_GITHUB_TOKEN} -r ${GHR_GITHUB_REPO} -u ${GHR_GITHUB_USERNAME} -replace "${CI_BUILD_REF_NAME}" master/'
    - 'ghr -t ${GHR_GITHUB_TOKEN} -r ${GHR_GITHUB_REPO} -u ${GHR_GITHUB_USERNAME} -replace "${CI_BUILD_REF_NAME}" doctorate/'
  only:
    - tags
  artifacts:
    name: "${CI_PROJECT_PATH_SLUG}_${CI_COMMIT_REF_NAME}"
    expire_in: 2 months
    paths:
      - '${DISTDIR}/*'
  tags:
    - docker
