compile-cls:
  image: philipptempel/docker-ubuntu-tug-texlive:latest
  stage: build
  script:
    - make clean
    - make all
  artifacts:
    name: "${CI_PROJECT_PATH_SLUG}_${CI_COMMIT_REF_NAME}"
    expire_in: 2 months
    paths:
      - dist
  tags:
    - docker

mirror2github:
  stage: deploy
  script:
    - git push --mirror https://${CI_GITHUB_USERNAME}:${CI_GITHUB_PASSWORD}@github.com/iswunistuttgart/latex-templates.git
  tags:
    - shell
    - linux
  only:
    - master
