compile-cls:
  image: python:2.7-alpine
  stage: build
  script:
    - python build.py
  artifacts:
    name: "${CI_PROJECT_PATH_SLUG}_${CI_COMMIT_REF_NAME}"
    paths:
      - dist
  tags:
    - docker

mirror2github:
  stage: deploy
  script:
    - git push --mirror https://philipptempel:6feeb59236f40796aa7f379fe92c58a44bd3a40a@github.com/iswunistuttgart/latex-templates.git
  tags:
    - shell
  only:
    - master
